#!/bin/bash
IFS=

OUTFILE="index.html"

function log {
	echo -e "\e[33mbuild\e[0m" $@ >&2
}


function build {
	local OUTFILE=$1
	shift;

	log "Building $OUTFILE"

	echo "" > $OUTFILE

	local MASKS=($@)
	for MASK in ${MASKS[@]}; do
		local FILES=$(find "$MASK" -type f)
		for file in ${FILES[@]}; do
			log "  Adding " $file
			cat $file >> $OUTFILE
		done
	done


	log "$OUTFILE is ready.\n"
}

build index.html tpl/prologue.html tools/*.html tpl/epilogue.html
build style.css assets/*.css
build app.js assets/*.js