#!/bin/bash

function log {
	_IFS=$IFS && IFS='' && echo -e "\e[33mbuild\e[0m" $@ >&2 && IFS=$_IFS
}


# Concatenates multiple files into single onr.
# Arguments:
#	$1 output file name
#	$@ file paths & masks to combine into $1
function build {
	local OUTFILE=$1
	shift;

	log "Building \e[33m\e[7m$OUTFILE\e[0m"

	echo "" > $OUTFILE

	local MASKS=($@)
	for MASK in ${MASKS[@]}; do
		local FILES=$(find "$MASK" -type f)
		for file in ${FILES[@]}; do
			log "  Adding " $file
			cat $file >> $OUTFILE
			echo -e '\n\n' >> $OUTFILE
		done
	done


	log "$OUTFILE is ready.\n"
}

# build index.html tpl/prologue.html tpl/components.html comp/*.html tpl/toolshed.html tools/*.html tpl/epilogue.html
# build index.html tpl/prologue.html tpl/components.html comp/*.html tpl/toolshed.html tpl/epilogue.html
build index.html tpl/prologue.html tpl/components.html comp/*.html tpl/toolshed.html tools/json.html tpl/epilogue.html
build style.css assets/*.css
build app.js assets/*.js