#!/bin/bash

# This script goes through the project sources and gathers referenced node_modules scripts.
# Then it deletes everything from the node_modules/ folder which is not used.

# Logging function.
function log {
	_IFS=$IFS && IFS='' && echo -e "\e[35m dist\e[0m" $@ >&2 && IFS=$_IFS
}

# Looking for NPM scripts referenced by sources in the folders.
SOURCES=("./tools/*" "./tpl/*")
SRCUSED=$(cat ${SOURCES[@]} | grep -E "<script[[:space:]]{0,1}src=\"./node_modules")
IFS=$'\n'

log "The used NPM scripts are"

# Trimming the grep output and getting file paths.
for S in ${SRCUSED[@]}; do
	SL=${S#*\"}
	SL=${SL%\"*}
	SL=${SL%\?*}
	NMUSED+=($SL)

	log "  \e[35m\e[7m$SL\e[0m"
done

function isused {
	for UF in ${NMUSED[@]}; do
		if [[ $UF == $1 ]]; then
			return 0
		fi
	done

	return 255
}

log "Deleting the rest from the ./node_modules folder..."

C=0
FILES=$(find ./node_modules/* -type f)
for FILE in ${FILES[@]}; do
	if ! isused $FILE; then
		rm $FILE
		let C=($C+1)
	fi
done

[[ -d ./node_modules/.bin ]] && rm -r ./node_modules/.bin

log "Done, deleted $C files."
