#!/bin/bash

# Folders to watch for changes in.
WATCHME=("./tools" "./tpl" "./assets")

echo "Watching" ${WATCHME[@]}

# Logging function.
function log {
	echo -e "\e[36mwatch\e[0m" $@ >&2
}

# Gets last modification time for a file.
function mtime {
	stat -c %Y "$1"
}

LASTMOD=0

# Loops through files in the $WATCHME dirs looking for the ones updated after the $LASTMOD time.
function findLastMTime {
	local MT=$LASTMOD
	for MASK in ${WATCHME[@]}; do
		local FOUNDFILES=$(find "$MASK" -type f)
		read -r -d $'\n' -a FILES <<< $FOUNDFILES
		for FILE in ${FILES[@]}; do
			local FMT=$(mtime "$FILE")

			if [[ $FMT > $LASTMOD ]]; then
				log "$FILE has changed."
			fi

			if [[ $FMT > $MT ]]; then
				MT=$FMT
			fi
		done
	done

	echo $MT
}

# Runs findLastMTime every second and triggers cmd/build if there were changes.
while [[ 1 = 1 ]]; do
	MT=$(findLastMTime)

	if [[ $MT > $LASTMOD ]]; then
		LASTMOD=$MT
		log "Gotta build!"
		echo ""
		cmd/build
		echo ""
	fi

	sleep 1s
done